version: "3.9"
services:
  my_model_util:
    container_name: my_model_util
    image: local/highwind/nllb-600m:latest
    command: --model_name=model
    working_dir: /app
    ports:
      - "8080:8080"